import { api } from "encore.dev/api";
import { getAuthData } from "~encore/auth"; // generated by Encore for your AuthData


// GET / (public)
export const root = api(
    { method: "GET", path: "/", expose: true }, // ensure reachable on gateway
    async () => ({ ok: true })                        // returns 200
);

// GET /health (public)
export const health = api(
    { method: "GET", path: "/health", expose: true }, // ensure reachable on gateway
    async () => ({ ok: true })                        // returns 200
);

// GET /health (public)
export const apiHealth = api(
    { method: "GET", path: "/api/health", expose: true }, // ensure reachable on gateway
    async () => ({ ok: true })                        // returns 200
);

interface HelloResponse { message: string; }

// GET /api/hello (requires auth)
export const hello = api<void, HelloResponse>(
    { auth: true, method: "GET", path: "/hello" },
    async () => {
        const { userID } = getAuthData()!; // safe: auth:true guarantees presence

        console.log('hello userID', userID)

        return { message: `Hello, ${userID}!` };
    },
);

// GET /api/hello (requires auth)
export const apiHello = api<void, HelloResponse>(
    { auth: true, method: "GET", path: "/api/hello" },
    async () => {
        const { userID } = getAuthData()!; // safe: auth:true guarantees presence

        console.log('apiHello userID', userID)

        return { message: `Hello, ${userID}!` };
    },
);
