x-logging: &default-logging
  driver: json-file
  options:
    max-size: "50m"
    max-file: "6"

networks:
  net:
    driver: bridge

services:
  traefik:
    image: traefik:v3.1
    restart: always
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/lib/platform/letsencrypt:/letsencrypt"
    networks: [net]
    env_file:
      - /etc/platform/env
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.tkd-basicauth.basicauth.users=${TRAEFIK_DASHBOARD_AUTH}"
      - "traefik.http.routers.tkd.rule=Host(`${TRAEFIK_DASHBOARD_DOMAIN}`)"
      - "traefik.http.routers.tkd.entrypoints=websecure"
      - "traefik.http.routers.tkd.tls=true"
      - "traefik.http.routers.tkd.service=api@internal"
      - "traefik.http.routers.tkd.middlewares=tkd-basicauth"
    logging: *default-logging

  db:
    image: encoredotdev/postgres:15
    container_name: postgres_db
    volumes:
      - /var/lib/platform/postgres:/var/lib/postgresql/data
      - /opt/platform/scripts/db/pg-init-scripts:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks: [net]
    env_file:
      - /etc/platform/env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1 -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    logging: *default-logging

  redis:
    image: redis:7.4-alpine
    container_name: redis
    volumes:
      - /var/lib/platform/redis:/data
    networks: [net]
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    logging: *default-logging

  logto:
    image: ghcr.io/logto-io/logto:1.18.0
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["sh", "-c", "./packages/cli/custom-setup/entrypoint.sh"]
    environment:
      - TRUST_PROXY_HEADER=1
      - ENDPOINT=https://${LOGTO_DOMAIN}
      - ADMIN_ENDPOINT=https://${LOGTO_ADMIN_DOMAIN}
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/logto
      - APP_NAME=platform
      - APP_DESCRIPTION=Baseline for organization workflows automation
      - APP_URI=${WEB_DOMAIN}
      - APP_URL=https://${WEB_DOMAIN}
      - LOGTO_APP_ID=${LOGTO_APP_ID}
      - LOGTO_APP_SECRET=${LOGTO_APP_SECRET}
      - LOGTO_APP_API_RESOURCE=https://${API_DOMAIN}/api
      - LOGTO_APP_API_EVENT_WEBHOOK_URL=https://${API_DOMAIN}/api/stripe/logto/webhook
      - LOGTO_APP_API_EVENT_WEBHOOK_SIGNING_KEY=${LOGTO_APP_API_EVENT_WEBHOOK_SIGNING_KEY}
      - LOGTO_MANAGEMENT_API_RESOURCE=https://${LOGTO_DOMAIN}/api
      - LOGTO_MANAGEMENT_API_APPLICATION_ID=${LOGTO_MANAGEMENT_API_APPLICATION_ID}
      - LOGTO_MANAGEMENT_API_APPLICATION_SECRET=${LOGTO_MANAGEMENT_API_APPLICATION_SECRET}
      - LOGTO_GOOGLE_CONNECTOR_ID=${LOGTO_GOOGLE_CONNECTOR_ID}
      - LOGTO_GOOGLE_CLIENT_ID=${LOGTO_GOOGLE_CLIENT_ID}
      - LOGTO_GOOGLE_CLIENT_SECRET=${LOGTO_GOOGLE_CLIENT_SECRET}
    volumes:
      - /opt/platform/scripts/logto/custom-setup:/etc/logto/packages/cli/custom-setup:ro
    networks: [net]
    env_file:
      - /etc/platform/env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logto.rule=Host(`${LOGTO_DOMAIN}`)"
      - "traefik.http.routers.logto.entrypoints=websecure"
      - "traefik.http.routers.logto.tls=true"
      - "traefik.http.routers.logto.tls.certresolver=myresolver"
      - "traefik.http.routers.logto.service=logto"
      - "traefik.http.services.logto.loadbalancer.server.port=3001"
      - "traefik.http.routers.logto-admin.rule=Host(`${LOGTO_ADMIN_DOMAIN}`)"
      - "traefik.http.routers.logto-admin.entrypoints=websecure"
      - "traefik.http.routers.logto-admin.tls=true"
      - "traefik.http.routers.logto-admin.tls.certresolver=myresolver"
      - "traefik.http.routers.logto-admin.service=logto-admin"
      - "traefik.http.services.logto-admin.loadbalancer.server.port=3002"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3001/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 40s
    logging: *default-logging

  api:
    image: ghcr.io/bartekus/platform/api:${IMAGE_TAG:-latest}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      traefik:
        condition: service_started
    env_file:
      - /etc/platform/env
    environment:
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks: [net]
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
    stop_grace_period: 60s
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/drain && exit 1; wget -qO- http://localhost:8000/health >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 20s
    logging: *default-logging

#  background:
#    image: ghcr.io/bartekus/platform/background:${IMAGE_TAG:-latest}
#    depends_on:
#      db:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#    env_file:
#      - /etc/platform/env
#    environment:
#      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#    networks: [net]
#    restart: always
#    healthcheck:
#      test: ["CMD-SHELL", "python -c 'import sys; sys.exit(0)'"]
#      interval: 30s
#      timeout: 5s
#      retries: 10
#    logging: *default-logging

  web:
    image: ghcr.io/bartekus/platform/web:${IMAGE_TAG:-latest}
    depends_on:
      api:
        condition: service_healthy
    networks: [net]
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${WEB_DOMAIN}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.services.web.loadbalancer.server.port=3001"
    stop_grace_period: 45s
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/drain && exit 1; wget -qO- http://localhost:3001/health >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 20s
    logging: *default-logging

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/platform/dozzle:/data
    networks: [net]
    env_file:
      - /etc/platform/env
    environment:
      DOZZLE_NO_ANALYTICS: "true"
      DOZZLE_AUTH_PROVIDER: "none"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`${DOZZLE_DOMAIN}`)"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.routers.dozzle.tls=true"
      - "traefik.http.routers.dozzle.tls.certresolver=myresolver"
      - "traefik.http.routers.dozzle.service=dozzle"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.dozzle-basicauth.basicauth.users=${DOZZLE_DASHBOARD_AUTH}"
      - "traefik.http.routers.dozzle.middlewares=dozzle-basicauth@docker"
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
    logging: *default-logging