/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignoutRouteImport } from './routes/signout'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthOrgOrgIdRouteImport } from './routes/_auth.org.$orgId'
import { Route as AuthOnboardingVerifyRouteImport } from './routes/_auth.onboarding.verify'
import { Route as AuthOnboardingSubscriptionRouteImport } from './routes/_auth.onboarding.subscription'
import { Route as AuthOnboardingProfileRouteImport } from './routes/_auth.onboarding.profile'
import { Route as AuthOnboardingOrganizationRouteImport } from './routes/_auth.onboarding.organization'
import { Route as AuthOrgOrgIdIndexRouteImport } from './routes/_auth.org.$orgId.index'
import { Route as AuthOrgOrgIdWorkspacesRouteImport } from './routes/_auth.org.$orgId.workspaces'
import { Route as AuthOrgOrgIdSettingsRouteImport } from './routes/_auth.org.$orgId.settings'
import { Route as AuthOrgOrgIdMembersRouteImport } from './routes/_auth.org.$orgId.members'
import { Route as AuthOrgOrgIdAdminRouteImport } from './routes/_auth.org.$orgId.admin'

const SignoutRoute = SignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOrgOrgIdRoute = AuthOrgOrgIdRouteImport.update({
  id: '/org/$orgId',
  path: '/org/$orgId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingVerifyRoute = AuthOnboardingVerifyRouteImport.update({
  id: '/onboarding/verify',
  path: '/onboarding/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingSubscriptionRoute =
  AuthOnboardingSubscriptionRouteImport.update({
    id: '/onboarding/subscription',
    path: '/onboarding/subscription',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthOnboardingProfileRoute = AuthOnboardingProfileRouteImport.update({
  id: '/onboarding/profile',
  path: '/onboarding/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingOrganizationRoute =
  AuthOnboardingOrganizationRouteImport.update({
    id: '/onboarding/organization',
    path: '/onboarding/organization',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthOrgOrgIdIndexRoute = AuthOrgOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthOrgOrgIdRoute,
} as any)
const AuthOrgOrgIdWorkspacesRoute = AuthOrgOrgIdWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthOrgOrgIdRoute,
} as any)
const AuthOrgOrgIdSettingsRoute = AuthOrgOrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthOrgOrgIdRoute,
} as any)
const AuthOrgOrgIdMembersRoute = AuthOrgOrgIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthOrgOrgIdRoute,
} as any)
const AuthOrgOrgIdAdminRoute = AuthOrgOrgIdAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthOrgOrgIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/onboarding/organization': typeof AuthOnboardingOrganizationRoute
  '/onboarding/profile': typeof AuthOnboardingProfileRoute
  '/onboarding/subscription': typeof AuthOnboardingSubscriptionRoute
  '/onboarding/verify': typeof AuthOnboardingVerifyRoute
  '/org/$orgId': typeof AuthOrgOrgIdRouteWithChildren
  '/org/$orgId/admin': typeof AuthOrgOrgIdAdminRoute
  '/org/$orgId/members': typeof AuthOrgOrgIdMembersRoute
  '/org/$orgId/settings': typeof AuthOrgOrgIdSettingsRoute
  '/org/$orgId/workspaces': typeof AuthOrgOrgIdWorkspacesRoute
  '/org/$orgId/': typeof AuthOrgOrgIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/onboarding/organization': typeof AuthOnboardingOrganizationRoute
  '/onboarding/profile': typeof AuthOnboardingProfileRoute
  '/onboarding/subscription': typeof AuthOnboardingSubscriptionRoute
  '/onboarding/verify': typeof AuthOnboardingVerifyRoute
  '/org/$orgId/admin': typeof AuthOrgOrgIdAdminRoute
  '/org/$orgId/members': typeof AuthOrgOrgIdMembersRoute
  '/org/$orgId/settings': typeof AuthOrgOrgIdSettingsRoute
  '/org/$orgId/workspaces': typeof AuthOrgOrgIdWorkspacesRoute
  '/org/$orgId': typeof AuthOrgOrgIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/callback': typeof CallbackRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/_auth/onboarding/organization': typeof AuthOnboardingOrganizationRoute
  '/_auth/onboarding/profile': typeof AuthOnboardingProfileRoute
  '/_auth/onboarding/subscription': typeof AuthOnboardingSubscriptionRoute
  '/_auth/onboarding/verify': typeof AuthOnboardingVerifyRoute
  '/_auth/org/$orgId': typeof AuthOrgOrgIdRouteWithChildren
  '/_auth/org/$orgId/admin': typeof AuthOrgOrgIdAdminRoute
  '/_auth/org/$orgId/members': typeof AuthOrgOrgIdMembersRoute
  '/_auth/org/$orgId/settings': typeof AuthOrgOrgIdSettingsRoute
  '/_auth/org/$orgId/workspaces': typeof AuthOrgOrgIdWorkspacesRoute
  '/_auth/org/$orgId/': typeof AuthOrgOrgIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/signin'
    | '/signout'
    | '/onboarding/organization'
    | '/onboarding/profile'
    | '/onboarding/subscription'
    | '/onboarding/verify'
    | '/org/$orgId'
    | '/org/$orgId/admin'
    | '/org/$orgId/members'
    | '/org/$orgId/settings'
    | '/org/$orgId/workspaces'
    | '/org/$orgId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/signin'
    | '/signout'
    | '/onboarding/organization'
    | '/onboarding/profile'
    | '/onboarding/subscription'
    | '/onboarding/verify'
    | '/org/$orgId/admin'
    | '/org/$orgId/members'
    | '/org/$orgId/settings'
    | '/org/$orgId/workspaces'
    | '/org/$orgId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/callback'
    | '/signin'
    | '/signout'
    | '/_auth/onboarding/organization'
    | '/_auth/onboarding/profile'
    | '/_auth/onboarding/subscription'
    | '/_auth/onboarding/verify'
    | '/_auth/org/$orgId'
    | '/_auth/org/$orgId/admin'
    | '/_auth/org/$orgId/members'
    | '/_auth/org/$orgId/settings'
    | '/_auth/org/$orgId/workspaces'
    | '/_auth/org/$orgId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  SigninRoute: typeof SigninRoute
  SignoutRoute: typeof SignoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/org/$orgId': {
      id: '/_auth/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/org/$orgId'
      preLoaderRoute: typeof AuthOrgOrgIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding/verify': {
      id: '/_auth/onboarding/verify'
      path: '/onboarding/verify'
      fullPath: '/onboarding/verify'
      preLoaderRoute: typeof AuthOnboardingVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding/subscription': {
      id: '/_auth/onboarding/subscription'
      path: '/onboarding/subscription'
      fullPath: '/onboarding/subscription'
      preLoaderRoute: typeof AuthOnboardingSubscriptionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding/profile': {
      id: '/_auth/onboarding/profile'
      path: '/onboarding/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof AuthOnboardingProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding/organization': {
      id: '/_auth/onboarding/organization'
      path: '/onboarding/organization'
      fullPath: '/onboarding/organization'
      preLoaderRoute: typeof AuthOnboardingOrganizationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/org/$orgId/': {
      id: '/_auth/org/$orgId/'
      path: '/'
      fullPath: '/org/$orgId/'
      preLoaderRoute: typeof AuthOrgOrgIdIndexRouteImport
      parentRoute: typeof AuthOrgOrgIdRoute
    }
    '/_auth/org/$orgId/workspaces': {
      id: '/_auth/org/$orgId/workspaces'
      path: '/workspaces'
      fullPath: '/org/$orgId/workspaces'
      preLoaderRoute: typeof AuthOrgOrgIdWorkspacesRouteImport
      parentRoute: typeof AuthOrgOrgIdRoute
    }
    '/_auth/org/$orgId/settings': {
      id: '/_auth/org/$orgId/settings'
      path: '/settings'
      fullPath: '/org/$orgId/settings'
      preLoaderRoute: typeof AuthOrgOrgIdSettingsRouteImport
      parentRoute: typeof AuthOrgOrgIdRoute
    }
    '/_auth/org/$orgId/members': {
      id: '/_auth/org/$orgId/members'
      path: '/members'
      fullPath: '/org/$orgId/members'
      preLoaderRoute: typeof AuthOrgOrgIdMembersRouteImport
      parentRoute: typeof AuthOrgOrgIdRoute
    }
    '/_auth/org/$orgId/admin': {
      id: '/_auth/org/$orgId/admin'
      path: '/admin'
      fullPath: '/org/$orgId/admin'
      preLoaderRoute: typeof AuthOrgOrgIdAdminRouteImport
      parentRoute: typeof AuthOrgOrgIdRoute
    }
  }
}

interface AuthOrgOrgIdRouteChildren {
  AuthOrgOrgIdAdminRoute: typeof AuthOrgOrgIdAdminRoute
  AuthOrgOrgIdMembersRoute: typeof AuthOrgOrgIdMembersRoute
  AuthOrgOrgIdSettingsRoute: typeof AuthOrgOrgIdSettingsRoute
  AuthOrgOrgIdWorkspacesRoute: typeof AuthOrgOrgIdWorkspacesRoute
  AuthOrgOrgIdIndexRoute: typeof AuthOrgOrgIdIndexRoute
}

const AuthOrgOrgIdRouteChildren: AuthOrgOrgIdRouteChildren = {
  AuthOrgOrgIdAdminRoute: AuthOrgOrgIdAdminRoute,
  AuthOrgOrgIdMembersRoute: AuthOrgOrgIdMembersRoute,
  AuthOrgOrgIdSettingsRoute: AuthOrgOrgIdSettingsRoute,
  AuthOrgOrgIdWorkspacesRoute: AuthOrgOrgIdWorkspacesRoute,
  AuthOrgOrgIdIndexRoute: AuthOrgOrgIdIndexRoute,
}

const AuthOrgOrgIdRouteWithChildren = AuthOrgOrgIdRoute._addFileChildren(
  AuthOrgOrgIdRouteChildren,
)

interface AuthRouteChildren {
  AuthOnboardingOrganizationRoute: typeof AuthOnboardingOrganizationRoute
  AuthOnboardingProfileRoute: typeof AuthOnboardingProfileRoute
  AuthOnboardingSubscriptionRoute: typeof AuthOnboardingSubscriptionRoute
  AuthOnboardingVerifyRoute: typeof AuthOnboardingVerifyRoute
  AuthOrgOrgIdRoute: typeof AuthOrgOrgIdRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthOnboardingOrganizationRoute: AuthOnboardingOrganizationRoute,
  AuthOnboardingProfileRoute: AuthOnboardingProfileRoute,
  AuthOnboardingSubscriptionRoute: AuthOnboardingSubscriptionRoute,
  AuthOnboardingVerifyRoute: AuthOnboardingVerifyRoute,
  AuthOrgOrgIdRoute: AuthOrgOrgIdRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CallbackRoute: CallbackRoute,
  SigninRoute: SigninRoute,
  SignoutRoute: SignoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
