/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignoutRouteImport } from './routes/signout'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionVerifyRouteImport } from './routes/subscription.verify'
import { Route as OnboardingSubscriptionRouteImport } from './routes/onboarding.subscription'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding.profile'
import { Route as OnboardingOrganizationRouteImport } from './routes/onboarding.organization'
import { Route as Auth_layoutRouteImport } from './routes/_auth.__layout'
import { Route as AuthDashboard_layoutRouteImport } from './routes/_auth.dashboard.__layout'
import { Route as AuthDashboardOrgOrgIdRouteImport } from './routes/_auth.dashboard.org.$orgId'
import { Route as AuthDashboardOrgOrgIdIndexRouteImport } from './routes/_auth.dashboard.org.$orgId.index'
import { Route as AuthDashboardOrgOrgIdWorkspacesRouteImport } from './routes/_auth.dashboard.org.$orgId.workspaces'
import { Route as AuthDashboardOrgOrgIdSettingsRouteImport } from './routes/_auth.dashboard.org.$orgId.settings'
import { Route as AuthDashboardOrgOrgIdMembersRouteImport } from './routes/_auth.dashboard.org.$orgId.members'
import { Route as AuthDashboardOrgOrgIdAdminRouteImport } from './routes/_auth.dashboard.org.$orgId.admin'

const AuthDashboardRouteImport = createFileRoute('/_auth/dashboard')()

const SignoutRoute = SignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/_auth/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionVerifyRoute = SubscriptionVerifyRouteImport.update({
  id: '/subscription/verify',
  path: '/subscription/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSubscriptionRoute = OnboardingSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingOrganizationRoute = OnboardingOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const Auth_layoutRoute = Auth_layoutRouteImport.update({
  id: '/_auth/__layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboard_layoutRoute = AuthDashboard_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardOrgOrgIdRoute = AuthDashboardOrgOrgIdRouteImport.update({
  id: '/org/$orgId',
  path: '/org/$orgId',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardOrgOrgIdIndexRoute =
  AuthDashboardOrgOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardOrgOrgIdRoute,
  } as any)
const AuthDashboardOrgOrgIdWorkspacesRoute =
  AuthDashboardOrgOrgIdWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthDashboardOrgOrgIdRoute,
  } as any)
const AuthDashboardOrgOrgIdSettingsRoute =
  AuthDashboardOrgOrgIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthDashboardOrgOrgIdRoute,
  } as any)
const AuthDashboardOrgOrgIdMembersRoute =
  AuthDashboardOrgOrgIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthDashboardOrgOrgIdRoute,
  } as any)
const AuthDashboardOrgOrgIdAdminRoute =
  AuthDashboardOrgOrgIdAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthDashboardOrgOrgIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/subscription': typeof OnboardingSubscriptionRoute
  '/subscription/verify': typeof SubscriptionVerifyRoute
  '/dashboard': typeof AuthDashboard_layoutRoute
  '/dashboard/org/$orgId': typeof AuthDashboardOrgOrgIdRouteWithChildren
  '/dashboard/org/$orgId/admin': typeof AuthDashboardOrgOrgIdAdminRoute
  '/dashboard/org/$orgId/members': typeof AuthDashboardOrgOrgIdMembersRoute
  '/dashboard/org/$orgId/settings': typeof AuthDashboardOrgOrgIdSettingsRoute
  '/dashboard/org/$orgId/workspaces': typeof AuthDashboardOrgOrgIdWorkspacesRoute
  '/dashboard/org/$orgId/': typeof AuthDashboardOrgOrgIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/subscription': typeof OnboardingSubscriptionRoute
  '/subscription/verify': typeof SubscriptionVerifyRoute
  '/dashboard': typeof AuthDashboard_layoutRoute
  '/dashboard/org/$orgId/admin': typeof AuthDashboardOrgOrgIdAdminRoute
  '/dashboard/org/$orgId/members': typeof AuthDashboardOrgOrgIdMembersRoute
  '/dashboard/org/$orgId/settings': typeof AuthDashboardOrgOrgIdSettingsRoute
  '/dashboard/org/$orgId/workspaces': typeof AuthDashboardOrgOrgIdWorkspacesRoute
  '/dashboard/org/$orgId': typeof AuthDashboardOrgOrgIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/_auth/__layout': typeof Auth_layoutRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/subscription': typeof OnboardingSubscriptionRoute
  '/subscription/verify': typeof SubscriptionVerifyRoute
  '/_auth/dashboard': typeof AuthDashboardRouteWithChildren
  '/_auth/dashboard/__layout': typeof AuthDashboard_layoutRoute
  '/_auth/dashboard/org/$orgId': typeof AuthDashboardOrgOrgIdRouteWithChildren
  '/_auth/dashboard/org/$orgId/admin': typeof AuthDashboardOrgOrgIdAdminRoute
  '/_auth/dashboard/org/$orgId/members': typeof AuthDashboardOrgOrgIdMembersRoute
  '/_auth/dashboard/org/$orgId/settings': typeof AuthDashboardOrgOrgIdSettingsRoute
  '/_auth/dashboard/org/$orgId/workspaces': typeof AuthDashboardOrgOrgIdWorkspacesRoute
  '/_auth/dashboard/org/$orgId/': typeof AuthDashboardOrgOrgIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/callback'
    | '/signin'
    | '/signout'
    | '/onboarding/organization'
    | '/onboarding/profile'
    | '/onboarding/subscription'
    | '/subscription/verify'
    | '/dashboard'
    | '/dashboard/org/$orgId'
    | '/dashboard/org/$orgId/admin'
    | '/dashboard/org/$orgId/members'
    | '/dashboard/org/$orgId/settings'
    | '/dashboard/org/$orgId/workspaces'
    | '/dashboard/org/$orgId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/callback'
    | '/signin'
    | '/signout'
    | '/onboarding/organization'
    | '/onboarding/profile'
    | '/onboarding/subscription'
    | '/subscription/verify'
    | '/dashboard'
    | '/dashboard/org/$orgId/admin'
    | '/dashboard/org/$orgId/members'
    | '/dashboard/org/$orgId/settings'
    | '/dashboard/org/$orgId/workspaces'
    | '/dashboard/org/$orgId'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/callback'
    | '/signin'
    | '/signout'
    | '/_auth/__layout'
    | '/onboarding/organization'
    | '/onboarding/profile'
    | '/onboarding/subscription'
    | '/subscription/verify'
    | '/_auth/dashboard'
    | '/_auth/dashboard/__layout'
    | '/_auth/dashboard/org/$orgId'
    | '/_auth/dashboard/org/$orgId/admin'
    | '/_auth/dashboard/org/$orgId/members'
    | '/_auth/dashboard/org/$orgId/settings'
    | '/_auth/dashboard/org/$orgId/workspaces'
    | '/_auth/dashboard/org/$orgId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  SigninRoute: typeof SigninRoute
  SignoutRoute: typeof SignoutRoute
  Auth_layoutRoute: typeof Auth_layoutRoute
  SubscriptionVerifyRoute: typeof SubscriptionVerifyRoute
  AuthDashboardRoute: typeof AuthDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/verify': {
      id: '/subscription/verify'
      path: '/subscription/verify'
      fullPath: '/subscription/verify'
      preLoaderRoute: typeof SubscriptionVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/subscription': {
      id: '/onboarding/subscription'
      path: '/subscription'
      fullPath: '/onboarding/subscription'
      preLoaderRoute: typeof OnboardingSubscriptionRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/organization': {
      id: '/onboarding/organization'
      path: '/organization'
      fullPath: '/onboarding/organization'
      preLoaderRoute: typeof OnboardingOrganizationRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_auth/__layout': {
      id: '/_auth/__layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Auth_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard/__layout': {
      id: '/_auth/dashboard/__layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboard_layoutRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/org/$orgId': {
      id: '/_auth/dashboard/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/dashboard/org/$orgId'
      preLoaderRoute: typeof AuthDashboardOrgOrgIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/org/$orgId/': {
      id: '/_auth/dashboard/org/$orgId/'
      path: '/'
      fullPath: '/dashboard/org/$orgId/'
      preLoaderRoute: typeof AuthDashboardOrgOrgIdIndexRouteImport
      parentRoute: typeof AuthDashboardOrgOrgIdRoute
    }
    '/_auth/dashboard/org/$orgId/workspaces': {
      id: '/_auth/dashboard/org/$orgId/workspaces'
      path: '/workspaces'
      fullPath: '/dashboard/org/$orgId/workspaces'
      preLoaderRoute: typeof AuthDashboardOrgOrgIdWorkspacesRouteImport
      parentRoute: typeof AuthDashboardOrgOrgIdRoute
    }
    '/_auth/dashboard/org/$orgId/settings': {
      id: '/_auth/dashboard/org/$orgId/settings'
      path: '/settings'
      fullPath: '/dashboard/org/$orgId/settings'
      preLoaderRoute: typeof AuthDashboardOrgOrgIdSettingsRouteImport
      parentRoute: typeof AuthDashboardOrgOrgIdRoute
    }
    '/_auth/dashboard/org/$orgId/members': {
      id: '/_auth/dashboard/org/$orgId/members'
      path: '/members'
      fullPath: '/dashboard/org/$orgId/members'
      preLoaderRoute: typeof AuthDashboardOrgOrgIdMembersRouteImport
      parentRoute: typeof AuthDashboardOrgOrgIdRoute
    }
    '/_auth/dashboard/org/$orgId/admin': {
      id: '/_auth/dashboard/org/$orgId/admin'
      path: '/admin'
      fullPath: '/dashboard/org/$orgId/admin'
      preLoaderRoute: typeof AuthDashboardOrgOrgIdAdminRouteImport
      parentRoute: typeof AuthDashboardOrgOrgIdRoute
    }
  }
}

interface OnboardingRouteRouteChildren {
  OnboardingOrganizationRoute: typeof OnboardingOrganizationRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
  OnboardingSubscriptionRoute: typeof OnboardingSubscriptionRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingOrganizationRoute: OnboardingOrganizationRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
  OnboardingSubscriptionRoute: OnboardingSubscriptionRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface AuthDashboardOrgOrgIdRouteChildren {
  AuthDashboardOrgOrgIdAdminRoute: typeof AuthDashboardOrgOrgIdAdminRoute
  AuthDashboardOrgOrgIdMembersRoute: typeof AuthDashboardOrgOrgIdMembersRoute
  AuthDashboardOrgOrgIdSettingsRoute: typeof AuthDashboardOrgOrgIdSettingsRoute
  AuthDashboardOrgOrgIdWorkspacesRoute: typeof AuthDashboardOrgOrgIdWorkspacesRoute
  AuthDashboardOrgOrgIdIndexRoute: typeof AuthDashboardOrgOrgIdIndexRoute
}

const AuthDashboardOrgOrgIdRouteChildren: AuthDashboardOrgOrgIdRouteChildren = {
  AuthDashboardOrgOrgIdAdminRoute: AuthDashboardOrgOrgIdAdminRoute,
  AuthDashboardOrgOrgIdMembersRoute: AuthDashboardOrgOrgIdMembersRoute,
  AuthDashboardOrgOrgIdSettingsRoute: AuthDashboardOrgOrgIdSettingsRoute,
  AuthDashboardOrgOrgIdWorkspacesRoute: AuthDashboardOrgOrgIdWorkspacesRoute,
  AuthDashboardOrgOrgIdIndexRoute: AuthDashboardOrgOrgIdIndexRoute,
}

const AuthDashboardOrgOrgIdRouteWithChildren =
  AuthDashboardOrgOrgIdRoute._addFileChildren(
    AuthDashboardOrgOrgIdRouteChildren,
  )

interface AuthDashboardRouteChildren {
  AuthDashboard_layoutRoute: typeof AuthDashboard_layoutRoute
  AuthDashboardOrgOrgIdRoute: typeof AuthDashboardOrgOrgIdRouteWithChildren
}

const AuthDashboardRouteChildren: AuthDashboardRouteChildren = {
  AuthDashboard_layoutRoute: AuthDashboard_layoutRoute,
  AuthDashboardOrgOrgIdRoute: AuthDashboardOrgOrgIdRouteWithChildren,
}

const AuthDashboardRouteWithChildren = AuthDashboardRoute._addFileChildren(
  AuthDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  CallbackRoute: CallbackRoute,
  SigninRoute: SigninRoute,
  SignoutRoute: SignoutRoute,
  Auth_layoutRoute: Auth_layoutRoute,
  SubscriptionVerifyRoute: SubscriptionVerifyRoute,
  AuthDashboardRoute: AuthDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
